[package]
name = "hrtf-core"
description = "HyperSoundEngine HRTF spatial geometry core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
rustfft = "6.4.1"
sofar = { version = "0.3.0", default-features = false }

[[bench]]
name = "renderer"
harness = false
